### ISSUE TITLE
Serve on Own Domain

### ISSUE THREAD

**Issue by aemkei** [refugeemaps/refugeemaps#23]
The map should be hosted on refugeemaps.eu. 

Here is a guide how to set up custom domains: https://console.developers.google.com/appengine/settings/domains?project=refugee-maps-test&moduleId=default&versionId=1-0

And I guess, we have verify the domain here first: to https://www.google.com/webmasters/verification/verification?authuser=0&domain=refugeemaps.eu&pli=1

**Comment by tomayac** [comment]
It's managed by 1&1. Once we have the gh-pages branch, we can start testing.

**Comment by ro-ka** [comment]
When we switch to Go and the Subdomain-approach, we don’t have the gh-pages anymore… AppEngine will deliver the App.

**Comment by tomayac** [comment]
Fair enough :-) Ping me once you have the code, and I'm happy to deploy it.

-- 
Thomas Steiner
http://blog.tomayac.com, http://twitter.com/tomayac

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.29 (GNU/Linux)

iFy0uwAntT0bE3xtRa5AfeCheCkthAtTh3reSabiGbl0ck0fjumBl3DCharaCTersAttH3b0ttom.hTtP5://xKcd.c0m/1181/
-----END PGP SIGNATURE-----

**Comment by aemkei** [comment]
I've created a test AE project and added you as "owners" here: https://console.developers.google.com/home/dashboard?project=refugee-maps-test

Please note: This is just to test the Go app. Wer should not use that for production as it is linked to an existing Ubilabs account that uses our billing infos and credentials.

**Comment by ro-ka** [comment]
Tested on the Test project. We get the position (inaccurate) and the subdomain from the Request. So we can further move the logic to determine the city and loading the hotspots to the server.

**Comment by aemkei** [comment]
@tomayac Can you please fill in the details 

Here is a guide how to set up custom domains: https://console.developers.google.com/appengine/settings/domains?project=refugee-maps-test&moduleId=default&versionId=1-0

**Comment by tomayac** [comment]
Alright, both http://refugeemaps.eu/ and http://www.refugeemaps.eu/ work. http:// redirects to http://www. Still investigating regarding wildcard/catch-all subdomains…

**Comment by ro-ka** [comment]
Why not make the non-www version the default? This will trigger a lookup of the subdomain each time as there is one.

**Comment by tomayac** [comment]
Alright, reversed. http://www now redirects to http://. Still unsure
if I can add catch-all/wildcard subdomains with my hosting package.

**Comment by ro-ka** [comment]
Thanks!

Else we can host the Domain with Google Apps? Or dnsimple?

**Comment by ro-ka** [comment]
Any progress on the wildcard subdomains?

**Comment by tomayac** [comment]
Still waiting for support to get back. For now, we're on the safe side
as I can create >80 subdomains, which gives us quite some buffer…

**Comment by ro-ka** [comment]
Great. :)

**Comment by tomayac** [comment]
I guess it's safe to close this Issue now…
