### ISSUE TITLE
Location-Specific URLs 

### ISSUE THREAD

**Issue by aemkei** [refugeemaps/refugeemaps#25]
As we want to serve the map for multiple locations, we need to find a way to serve them via different URLs. The easiest way would be to use a hash or query string. A path or subdomain would be even better. 

* hash: refugeemaps.eu/#location
* query: refugeemaps.eu/?l=location
* path: refugeemaps.eu/location
* subdomain: location.refugeemaps.eu

Question is, if/how we can do that with our static site. It that possible with custom domains on Github?

**Comment by tomayac** [comment]
"Go" for Go! All ready as of closing https://github.com/refugeemaps/refugeemaps/issues/27.
