### ISSUE TITLE
Use new Spreadsheets

### ISSUE THREAD

**Issue by ro-ka** [refugeemaps/refugeemaps#29]
@mrMetalWood started this in an outdated Branch:

> So hier ist der diff meines work in progress: https://github.com/refugeemaps/refugeemaps/commit/d0cea1b0b57c4ba29b091585ee86678a9c59dfda
Zeile 17 bis 77 wäre quasi das neue spreadsheet. Man bekommt da ein .tsv zurück. Und ich hatte das dann in die Objekt struktur umgebaut wie sie vorher auch war. Die einzige Sache die da noch offen ist die Handhabung der Kategorien. In dem Work in Progress bekommen im Moment alle die kategorie 'church' da es im spreadsheet keine zelle mit der kategorie gibt. Bisher sind da nur emoticons drin.

Link to Hamburg Sheet: https://docs.google.com/spreadsheets/d/15Na8ihDIljcRatsPkNQFA1rQLM6C08AC0VJVyGFKioI/pub?gid=81535625&single=true&output=tsv

**Comment by tomayac** [comment]
The "legend" for the categories is in the first line of the file, please see

**Comment by tomayac** [comment]
The legend for the categories is in the first line of the file, please see https://github.com/refugeemaps/refugeemaps/issues/22#issuecomment-154168331 for details. 

[Switching tabs on mobile accidentally closed the issue, can't edit comments on mobile]
