### ISSUE TITLE
Update Icons

### ISSUE THREAD

**Issue by ro-ka** [refugeemaps/refugeemaps#35]
Most of the icons should be updated:

- [x] The icons for places need to be updated.
  - [x] In the filters, the pure [Maki](https://www.mapbox.com/maki/) icon should appear.
  - [x] On the map they should be with a red background.
- [x] A selected place get’s the standard red marker.
- [x] The user icon will be a blue circle.

See Design (#26) for more details.

**Comment by aemkei** [comment]
The Maki icon's SVG is quite a mess. But using https://github.com/svg/svgo we can reduce the transforms.

**Comment by aemkei** [comment]
Here is a quick demo: https://jsbin.com/matulot/

**Comment by tomayac** [comment]
Not sure if this works (not natively probably, as I guess letters are
defined as [a-zA-Z] in
https://developers.google.com/maps/documentation/javascript/3.exp/reference#MarkerLabel),
but maybe we can use the same emoji icons as in the spreadsheet?!

**Comment by aemkei** [comment]
@tomayac Unfortunately we can't use Emojis as the are not drawn correctly. See: https://output.jsbin.com/jamoba

**Comment by tomayac** [comment]
That's what I thought :-/ too narrow definition of "character".

-- 
Thomas Steiner
http://blog.tomayac.com, http://twitter.com/tomayac

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.29 (GNU/Linux)

iFy0uwAntT0bE3xtRa5AfeCheCkthAtTh3reSabiGbl0ck0fjumBl3DCharaCTersAttH3b0ttom.hTtP5://xKcd.c0m/1181/
-----END PGP SIGNATURE-----
