### ISSUE TITLE
Links to Google+ and Twitter

### ISSUE THREAD

**Issue by ro-ka** [refugeemaps/refugeemaps#38]
We want to link to this Github repo in the sidebar. 

![image](https://cloud.githubusercontent.com/assets/1521/11183715/b73c3f7c-8c73-11e5-8683-67ee2f6a0117.png)

* [ ] remove Twitter and G+ icon
* [ ] URL to link to: https://github.com/refugeemaps/refugeemaps
* [ ] use this icon: https://materialdesignicons.com/icon/github-box

**Comment by aemkei** [comment]
We could also link to this GitHub repository instead. 

@tomayac What do you think? Will there be a Twitter / G+ Account for this project?

**Comment by tomayac** [comment]
Let's link to the repo for now, we can think of social media profiles
later on (FWIW, @RefugeeMaps is already taken).

**Comment by aemkei** [comment]
okay, than let's switch to a single icon for Github and link to this repo. (I'll update the description in a second).
