### ISSUE TITLE
Location/Sheet Mapping

### ISSUE THREAD

**Issue by aemkei** [refugeemaps/refugeemaps#39]
Were should we do the mapping for the locations?

In the application we need the following information: 

1. ID (=subdomain = no special chars)
2. Name (to display in list and map title)
3. Latitude / Longitude (for auto mapping on main site)
4. Sheet URL (to load data from)

**Comment by tomayac** [comment]
I'd go with a similar approach as with the data spreadsheet: mapping
spreadsheet published to the Web as ```.tsv``` file with the columns
```id\tname\tlat\tlong\tsheetid```.

**Comment by ro-ka** [comment]
I suggest to make the mapping of the subdomain / location on the server. We get the needed data by AppEngine and then the client doesn’t need to communicate with Spreadsheets at all.

The flow looks like this then:
* Open refugeemaps.com
* Go server finds the correct city via the subdomain or position of the user
* Return the API endpoint refugeemaps.com/_api/hotspots/hamburg.json with the HTML
* Client asks the API  endpoint to get the hotspots.

There will be only one single AJAX call by the client, the rest is handled server side (faster). Also, we would have an wrapper which allows people to build native apps or other apps with this.

**Comment by aemkei** [comment]
The sheet is available as an TSV here: https://docs.google.com/spreadsheets/d/1pg-73mda1ZBtGZAFdkt2gh6XXCHxPuYnaWhNQbrcDx0/pub?gid=0&single=true&output=tsv

See the original sheet: https://docs.google.com/spreadsheets/d/1pg-73mda1ZBtGZAFdkt2gh6XXCHxPuYnaWhNQbrcDx0/edit#gid=0

**Comment by tomayac** [comment]
Note: you want an easy workflow like simply appending a new row to a
spreadsheet for adding new locations.

**Comment by aemkei** [comment]
We can make this process easier after the initial launch. I guess it is OK to work with the plain sheet, as only some people have access and we are not (yet) adding hundreds of locations per day.

**Comment by tomayac** [comment]
SGTM. The "easy" mostly refers to the content admin side, so I guess
spreadsheets is good enough. We should cache both quite aggressively with
Service Worker, so I guess it's fine (current "cold-start" weight for
http://refugee-maps-test.appspot.com/ is 934 KB).
