### ISSUE TITLE
Categories & Icons

### ISSUE THREAD

**Issue by aemkei** [refugeemaps/refugeemaps#42]
We should decide on a first set of categories. In the old sheet we used the following, based on the offline map:

> mosque, church, bank, call-shop, supermarket, pharmacy, laundry, playground, football, basketball, table-tennis, skateboard, library, public-restroom, culture

The new one has:

> Religion, Finance, Communication, Shopping, Health, Sports, Kids, Parks, Cafés, Authorities, Culture

As we can't use Emojis, we have to switch to map icons such as https://www.mapbox.com/maki.

How about these:

* ![religious-muslim-18](https://cloud.githubusercontent.com/assets/1521/11189971/8498cfc0-8c93-11e5-9964-ec20f60f5d1e.png) Religion
* ![bank-18](https://cloud.githubusercontent.com/assets/1521/11190000/a3f5b4f0-8c93-11e5-84ba-bf263c107474.png) Finance
* ![mobilephone-18](https://cloud.githubusercontent.com/assets/1521/11189995/9b1ce34e-8c93-11e5-897b-e69e56c9cc6a.png) Communication
* ![shop-18](https://cloud.githubusercontent.com/assets/1521/11190016/b4410b8e-8c93-11e5-9d9c-dec8a1c31961.png)  Shopping
* ![hospital-18](https://cloud.githubusercontent.com/assets/1521/11190025/be0c3b70-8c93-11e5-9603-51d6b589edae.png) Health
* ![pitch-18](https://cloud.githubusercontent.com/assets/1521/11190032/ce918540-8c93-11e5-8edd-5e612137de15.png) Sports
* ![playground-18](https://cloud.githubusercontent.com/assets/1521/11190033/d8378c20-8c93-11e5-9f0f-6e2e1509e8f9.png) Kids
* ![garden-18](https://cloud.githubusercontent.com/assets/1521/11190044/e8871cd0-8c93-11e5-97fa-6d47f1ed3eae.png) Parks
* ![cafe-18](https://cloud.githubusercontent.com/assets/1521/11190060/fa490514-8c93-11e5-8185-7dff75dae830.png) Cafés
* ![commercial-18](https://cloud.githubusercontent.com/assets/1521/11190104/29ff2b12-8c94-11e5-9023-cf9cfcf00f4a.png) Authorities
* ![town-hall-18](https://cloud.githubusercontent.com/assets/1521/11190161/7e639f76-8c94-11e5-816b-9462e576f4a1.png) Culture

PS: We had a lot of "public toilet" POIs in the map and put them under "Health" for now.

**Comment by ro-ka** [comment]
Why not keep the toilets then? And for religion: Do we want to seperate churchs and mosques or put them under the same category? Is the icon obvious then for christians?

**Comment by aemkei** [comment]
I thought the same about the toilets and churches. @tomayac What do you think? should we change that in the sheets?

* ![toilets-18](https://cloud.githubusercontent.com/assets/1521/11207573/419ed65a-8d16-11e5-9405-6db3d2b2aa65.png) toilets
* ![religious-muslim-18](https://cloud.githubusercontent.com/assets/1521/11207554/2b505b08-8d16-11e5-954d-8d444d3a9c13.png) muslim
* ![religious-jewish-18](https://cloud.githubusercontent.com/assets/1521/11207555/2b511d18-8d16-11e5-971f-9380cc2687dd.png) jewish
* ![religious-christian-18](https://cloud.githubusercontent.com/assets/1521/11207553/2b4c47ac-8d16-11e5-934b-fa8986d81e08.png) christian

I would also suggest to use IDs without special chars (such as in "Cafés") as it might cause problems in the code.

**Comment by tomayac** [comment]
We can easily add new categories to the existing ones (I just did
this). Religion is a heavily loaded topic really. We also do not want
to list mosques blindly
(http://www.zeit.de/2015/06/salafismus-prediger-barmbek-verfassungsschutz).
I am against making it too complex with too many tabs for the same
concept (place of worship). If you know a neutral way to represent
worship? How about 🙏?

**Comment by aemkei** [comment]
I've created the icons for the categories here: https://jsbin.com/matulot/

**Comment by tomayac** [comment]
Thanks! Can you still flip the half-moon for the praying hands? Culture
might be better represented with the performing arts masks (
http://emojipedia.org/performing-arts/).

**Comment by aemkei** [comment]
There is no "praying hand" symbol in the Maki set: https://www.mapbox.com/maki/ – it is also super hard to read and might be confusing for Muslim, because they do open their hands while praying.

And I'd like to keep the building for "culture", as we are referring libraries, museums, …

**Comment by tomayac** [comment]
> There is no "praying hand" symbol in the Maki set: https://www.mapbox.com/maki/
Maybe the "place of worship" icon? It looks a bit like a space shuttle…

> And I'd like to keep the building for "culture", as we are referring libraries, museums, …
Fair enough. Some overlap with the authorities icon, but works :-)

**Comment by aemkei** [comment]
Okay, let's use the "worship" icon. See: https://output.jsbin.com/matulot/

**Comment by tomayac** [comment]
LGTM, thanks :-D
