### ISSUE TITLE
Wrong Geocodes

### ISSUE THREAD

**Issue by aemkei** [refugeemaps/refugeemaps#44]
Looks like the sheet is overriding an address with something different.

Try to write "`Martinistraße 52, Hamburg`" into the address field and it will be replaced by "Villa Garbrecht" (which is wrong). Unfortunately we found no way to fix that.

Eg. see "Flüchtlingsambulanz" in this [sheet](https://docs.google.com/spreadsheets/d/15Na8ihDIljcRatsPkNQFA1rQLM6C08AC0VJVyGFKioI/edit#gid=938800748).

**Comment by tomayac** [comment]
Seems to be the correct address, also look at (Street View)[
https://www.google.com/maps/place/villa+garbrecht+hamburg/@53.5896226,9.9775206,3a,75y,334.2h,90t/data=!3m7!1e1!3m4!1sRwOR8NN3G46I0UKP6BMUbg!2e0!7i13312!8i6656!4b1!4m2!3m1!1s0x0:0xccf6efb4b845e45e!6m1!1e1],
it's a villa indeed. The field is filled with whatever the Geocoder returns
as the street address.

**Comment by aemkei** [comment]
You are right: It is not a bug, it is a feature!
