### ISSUE TITLE
Tweak Styling of Categories

### ISSUE THREAD

**Issue by aemkei** [refugeemaps/refugeemaps#48]
![image](https://cloud.githubusercontent.com/assets/1521/11214028/6c6f8dec-8d3f-11e5-9c23-6c1a429e759c.png)

* [x] vertically center icons
* [x] make bottom line 100% wide
* [x] color: `#757575`

**Comment by ro-ka** [comment]
In the design the bottom line was not 100%.

**Comment by aemkei** [comment]
Dario said: 

> "Das ist falsch". 
> "Das muss durch gehen". 
> "Aber links nicht". 
> "Ich schick euch mal einen Screen …"

**Comment by aemkei** [comment]
![image](https://cloud.githubusercontent.com/assets/1521/11214312/d24c81dc-8d40-11e5-92b9-463f0b8ee3ee.png)

So, the line should stop at the left as it is now but no padding on the right. And when hovering the background must include the line.
