### ISSUE TITLE
Filter empty places

### ISSUE THREAD

**Issue by ro-ka** [refugeemaps/refugeemaps#65]
There seem to be places, that don’t even have a name. What about those that don’t have a name? Remove them?

**Comment by aemkei** [comment]
That might be an error. Here is the old doc, maybe there are still in there: 
https://docs.google.com/spreadsheets/d/1M5INJw-LvHfRzl0VleYVKWdiGOS1LE1uF-4ePlCQeYQ/edit

**Comment by ro-ka** [comment]
Nonetheless, I made an PR catching these. Doesn’t make sense to show empty infoboxes…

**Comment by tomayac** [comment]
I fixed the error in the spreadsheet. As a sanity check on the client,
it's always good to require at least a name and description plus
lat/long at least.

**Comment by ro-ka** [comment]
Okay, so I’ll filter out those that don’t have these fields in the Go Server.

**Comment by ro-ka** [comment]
Updated the PR
