### ISSUE TITLE
API extension

### ISSUE THREAD

**Issue by ro-ka** [refugeemaps/refugeemaps#71]
Currently the API has only one JSON endpoint: `/_api/hotspots/{locationId}.json`.

For allowing other apps to use the abstracted (and cached) API, it needs to be extended.
Suggestion:
* [x] `/_api/locations/`  --> Return all the available cities/locations with Name, Id and Position
* [x] `/_api/locations/{locationId}/` --> Returns pois, categories and languages for the location
* [x] `/_api/locations/{locationId}/pois/` -->  Return the pois for one location
* [x] `/_api/locations/{locationId}/categories/` -->  Return the categories for one location
* [x] `/_api/locations/{locationId}/languages/` -->  Return the languages for one location
* [x] `/_api/hotspots/{locationId}.json` --> Return the pois for one location (implemented already). Shall redirect to the endpoint above soon and then be deprecated.

**Comment by g-mac** [comment]
:+1:

**Comment by g-mac** [comment]
Can anybody implement this? Would be great.. Especially no.1 and 2 since I would like to fetch the data for my android project.. @ro-ka machst du das noch?

**Comment by ro-ka** [comment]
Will implement, tomorrow maybe.

**Comment by ro-ka** [comment]
(btw, I started working on this.)

**Comment by g-mac** [comment]
:tada:

**Comment by ro-ka** [comment]
Opened a PR, but I guess it’ll be merged and deployed on monday.

**Comment by g-mac** [comment]
Thanks a lot! =)
