### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by AppWerft** [refugeemaps/refugeemaps#96]
Hi,
I'm looking for icons  fpr markers in PNG. I only see SVG. How can I convert?

**Comment by aemkei** [comment]
We used the markers from the Maki project: https://www.mapbox.com/maki/

They provide different sizes and formats.

**Comment by AppWerft** [comment]
Thanks. is there a mapping between category and name of image? I need it for [android app](https://github.com/AppWerft/RefugeeMaps)

**Comment by aemkei** [comment]
Here is a "visual" list of the icons we used: https://output.jsbin.com/matulot/

**Comment by aemkei** [comment]
And the list of icons, we used:

* soccer
* mobilephone
* bank
* place-of-worship
* shop
* hospital
* playground
* garden
* cafe
* commercial
* town-hall
* toilets

**Comment by AppWerft** [comment]
Thanks, now I now:

soccer == sports
mobilephone == communication

……

It keeps still the question how I can convert:

sport: "M.5-7C-3.08-7-6-4.08-6-.5S-3.08 6 .5 6 7 3.08 7-.5 4.08-7 
.5-7zm0 1.147c2.04 0 3.803 1.127 4.708 2.796-.854.566-1.638.862-1.65 
1.41-.006.382 0 .49 0 .765 0 .382.2.874.766 1.147L5.662.91c-.153.566-.4 
1.08-.717 
1.553l-1.004-.67c-.572-.38-1.146-.636-1.528-.38l-1.147.763c-.53.354-.475.765-.383 
1.147l.36 1.482c-.244.033-.49.047-.742.047-.53 
0-1.047-.074-1.53-.215V3.323c0-.765-.382-1.147-.764-1.53-.382-.382-.765-.764-1.53-.764h-1.314c-.142-.484-.215-1-.215-1.53 
0-2.966 2.388-5.353 5.353-5.353zm-2.294 2.676l-.382 
1.53c-.11.434-.398.882 0 
1.147l1.147.765C-.264.775.074.48.5.265l.765-.383c.57-.285.764-.382.764-1.147v-1.53c0-.38.005-.61-.765-.764l-1.912-.38c-.8-.16-.952-.02-1.147.764z", 


into a PNG. I don't  know a tool for it.



Am 19/11/15 um 19:08 schrieb Martin Kleppe:
>
> And the list of icons, we used:
>
>   * soccer
>   * mobilephone
>   * bank
>   * place-of-worship
>   * shop
>   * hospital
>   * playground
>   * garden
>   * cafe
>   * commercial
>   * town-hall
>   * toilets
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/refugeemaps/refugeemaps/issues/96#issuecomment-158140588>.
>

-- 
*Dipl.-Ing. Rainer Schleevoigt*
Certified TYPO3 Integrator
Certified Titanium App Developer

	Novalisweg 10
22303 Hamburg
℡ 040 60812460
|Ust-ID: DE239491976|||||||

**Comment by ro-ka** [comment]
Take a look at the site @aemkei linked: https://www.mapbox.com/maki/  You can find the PNG there.
